name: deskpixel
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^5.5.0
  flutter_advanced_networkimage: ^0.7.0
  cloud_firestore: ^0.13.7
  flutter_svg: ^0.17.1
  shared_preferences: ^0.5.8
  provider: ^4.3.1
  firebase_admob: ^0.9.3+2
  permission_handler: ^5.0.1+1
  dio: ^3.0.9
  photo_view: ^0.9.2
  http: ^0.12.1
  flutter_staggered_grid_view: ^0.3.0
  image_gallery_saver: ^1.5.0

flutter:

  uses-material-design: true

  assets:
   - Assets/Images/linkedin.svg
   - Assets/Images/Astronaut.svg
   - Assets/Images/instagram.svg
   - Assets/Images/background.svg
   - Assets/Images/ic_launcher.png
   - Assets/Images/github.png
   - Assets/Images/loading.gif
   - Assets/Images/drawerimg.jpg

  fonts:
  - family: GoogleSans
    fonts:
      - asset: Assets/Fonts/GoogleSans-Regular.ttf
      - asset: Assets/Fonts/GoogleSans-Bold.ttf